server:
  port: 8080

spring:
  application:
    name: backend
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true # for postgresql
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_nationalized_character_data: true
        temp:
          use_jdbc_metadata_defaults: false
        show_sql: false
        default_schema: public
  jwt:
    secure: false
    sameSite: "Lax"
    duration: 3600000 # 1 min
    secret: "7A25432A462D4A614E645267556B58703272357538782F413F4428472B4B6250" # random string in base64