spring:
  profiles:
    active: [ prod ]

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATASOURCE_URL}
    driverClassName: org.postgresql.Driver
  security:
    user:
      name: admin
      password: admin
  application:
    name: backend
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true # for postgresql
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_nationalized_character_data: true
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: public
  jwt:
    secure: false
    sameSite: "Lax"
    duration: 86400000 # 1 day
    secret: ${JWT_SECRET}
