name: Build frontend
run-name: "Run ${{github.run_id}}, triggered by ${{github.actor}}"

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: STIN-semestral-project/frontend
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: npm install and npm run CI commands
        run: |
          npm i
          npm run test:ci
          npm run build:ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: frontend
          slug: ${{ github.repository }}
          file: frontend/coverage/lcov-report/lcov.info
