name: Build backend
run-name: "Run ${{github.run_id}}, triggered by ${{github.actor}}"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Build and test backend
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          cache-dependency-path: |
            backend/*.gradle*
            backend/**/gradle-wrapper.properties
      - run: ./gradlew build --no-daemon

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: backend
          file: backend/build/reports/jacoco/test/html/jacocoTestReport.xml
