name: Deploy
run-name: "Run ${{github.run_id}}, triggered by ${{github.actor}}"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

defaults:
  run:
    working-directory: backend

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 for backend
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          generate-job-summary: true
          add-job-summary-as-pr-comment: on-failure
          cache-disabled: true
      - name: Set execute permissions for backend gradlew
        run: chmod +x gradlew

      - name: Build backend and run tests with Gradle Wrapper
        run: ./gradlew build

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set env
        run: echo "DATE=$(date +%s)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/docker/Dockerfile-backend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend:${{ env.DATE }}

      - name: Login to Heroku Container Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build Docker image
        run: docker build -t registry.heroku.com/${{ secrets.HEROKU_BACKEND_NAME }}/backend .

      - name: Push Docker image to Heroku Container Registry
        run: docker push registry.heroku.com/${{ secrets.HEROKU_BACKEND_NAME }}/backend

      - name: Release Docker image on Heroku
        run: heroku container:release -a ${{ secrets.HEROKU_BACKEND_NAME }} backend
