name: Deploy
run-name: "Run ${{github.run_id}}, triggered by ${{github.actor}}"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - name: Setup and Run Tests
        run: |
          docker-compose build
          docker-compose run web rake db:setup
          docker-compose run web rspec

      - uses: akhileshns/heroku-deploy@v3.12.12 # This action deploys the content on Heroku
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}} #The Heroku api key we stored on our repo secret
          heroku_app_name: "moc-backend-weather-app" #The name of your heroku app - Must be unique in Heroku
          heroku_email: "stepan.moc@tul.cz" #Your heroku yuser name