name: Deploy
run-name: "Run ${{github.run_id}}, triggered by ${{github.actor}}"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

defaults:
  run:
    working-directory: backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag registry.heroku.com/moc-backend-weather-app/web

      - name: Log in to Heroku Container Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=stepan.moc@tul.cz --password-stdin registry.heroku.com

      - name: Push Docker image to Heroku Container Registry
        run: docker push registry.heroku.com/moc-backend-weather-app/web

      - name: Release the image on Heroku
        run: heroku container:release web --app moc-backend-weather-app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}