name: Deploy app
run-name: "Run ${{github.run_id}}, triggered by ${{github.actor}}"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy backend to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_BACKEND_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: false
          appdir: 'backend'
          procfile: 'web: java $JAVA_OPTS -Dserver.port=$PORT -jar build/libs/backend-1.0.0.jar --spring.profiles.active=prod'

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy backend to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_FRONTEND_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: false
          appdir: 'frontend'
