name: Deploy
run-name: "Run ${{github.run_id}}, triggered by ${{github.actor}}"

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "moc-weather-app" #Must be unique in Heroku
          heroku_email: "stepan.moc@tul.cz"
          procfile: "web: java -Dspring.profiles.active=prod -Dserver.port=$PORT -jar build/libs/backend-0.0.1-SNAPSHOT.jar"