name: Deploy
run-name: "Run ${{github.run_id}}, triggered by ${{github.actor}}"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

defaults:
  run:
    working-directory: backend

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s) --build-arg ENV_FILE=./src/main/resources/application-prod.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - uses: actions/checkout@v2
      - name: Setup and Run Tests
        run: |
          docker-compose build
          docker-compose run web rake db:setup
          docker-compose run web rspec

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "moc-backend-weather-app"
          heroku_email: "stepan.moc@tul.cz"