name: Deploy
run-name: "Run ${{github.run_id}}, triggered by ${{github.actor}}"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      -
defaults:
  run:
    working-directory: backend

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Deploy backend to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_BACKEND_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: false
          branch: 'main'
          appdir: 'backend'
          procfile: 'web: java -Dserver.port=8080 -jar build/libs/backend-1.0.0.jar --spring.profiles.active=prod'
