name: Deploy
run-name: "Run ${{github.run_id}}, triggered by ${{github.actor}}"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

defaults:
  run:
    working-directory: backend

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 for backend
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          generate-job-summary: true
          add-job-summary-as-pr-comment: on-failure
          cache-disabled: true
      - name: Set execute permissions for backend gradlew
        run: chmod +x gradlew

      - name: Build backend and run tests with Gradle Wrapper
        run: ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Heroku Container Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build and push Docker image to Heroku
        run: docker buildx build --file Dockerfile-backend --tag registry.heroku.com/${{ secrets.HEROKU_BACKEND_NAME }}/web .

      - name: Deploy to Heroku
        run: docker push registry.heroku.com/${{ secrets.HEROKU_BACKEND_NAME }}/web

      - name: Release to Heroku
        run: heroku container:release web -a ${{ secrets.HEROKU_BACKEND_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}