name: Main
run-name: "Run ${{github.run_id}}, triggered by ${{github.actor}}"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
     - uses: actions/checkout@v4
     - name: Set up JDK 17 for backend
       uses: actions/setup-java@v4
       with:
        java-version: 17
        distribution: temurin

     - name: setup Gradle
       uses: gradle/actions/setup-gradle@v3
       with:
         generate-job-summary: true
         add-job-summary-as-pr-comment: on-failure
         cache-disabled: true

     - name: Set execute permissions for backend gradlew
       run: chmod +x gradlew

     - name: Build backend and run tests with Gradle Wrapper
       run: ./gradlew build

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  test-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Build backend and run tests with Gradle Wrapper
        run: ./gradlew test

  test-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: npm run test

  backend-coverage:
    runs-on: ubuntu-latest
    needs: test-backend
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: backend
          file: backend/build/reports/jacoco/test/html/jacocoTestReport.xml

  frontend-coverage:
    runs-on: ubuntu-latest
    needs: test-frontend
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: frontend
          file: frontend/coverage/cobertura-coverage.xml

  dependency-review:
      runs-on: ubuntu-latest
      needs: [build-backend, build-frontend]
      steps:
        - name: 'Checkout repository'
          uses: actions/checkout@v4
        - name: 'Dependency Review'
          uses: actions/dependency-review-action@v4
          with:
            comment-summary-in-pr: always