name: Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout backend repo
        uses: actions/checkout@v4
      - name: Set up JDK 17 for backend
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle for backend
        uses: gradle/setup-gradle@v1
        with:
          gradle-version: '7.x'

      - name: Set execute permissions for backend gradlew
        run: chmod +x gradlew

      - name: Build backend and run tests with Gradle Wrapper
        run: ./gradlew build

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v4
      - name: Use Node.js 20.x for frontend
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

  test-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout backend repo
        uses: actions/checkout@v4
      - name: Run backend tests
        run: ./gradlew test

  test-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v4
      - name: Run frontend tests
        run: npm run test

  backend-coverage:
    runs-on: ubuntu-latest
    needs: test-backend
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout backend repo
        uses: actions/checkout@v4
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: backend
          file: build/reports/jacoco/test/html/jacocoTestReport.xml

  frontend-coverage:
    runs-on: ubuntu-latest
    needs: test-frontend
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v4
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: frontend
          file: coverage/cobertura-coverage.xml

  dependency-review:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v2
        with:
          comment-summary-in-pr: always