name: Development
run-name: "Run ${{github.run_id}}, triggered by ${{github.actor}}"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 for backend
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
          cache-dependency-path: |
            backend/*.gradle*
            backend/**/gradle-wrapper.properties

      - name: Build backend with Gradle Wrapper
        run: ./gradlew build -x test

  backend-test:
    name: Test backend
    runs-on: ubuntu-latest
    needs: build-backend
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Run tests with Gradle Wrapper
        run: ./gradlew jacocoTestReport

  backend-coverage:
    name: Backend coverage
    runs-on: ubuntu-latest
    needs: backend-test
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: backend
          file: backend/build/reports/jacoco/test/html/jacocoTestReport.xml
