name: STIN - Build backend and frontend on pull request
on:
  push:
    branches: 
      - "main"
  pull_request:
    branches:
      - "main"
permissions:
  contents: read
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-pull-request"
  cancel-in-progress: true
jobs:
  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    container:
      image: public.ecr.aws/docker/library/gradle:jdk17
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./gradlew build --no-daemon
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: backend
          files: backend/build/reports/jacoco/test/html/jacocoTestReport.xml
  build-frontend:
    name: Build and test frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    container:
      image: public.ecr.aws/docker/library/node:20.18.3-slim
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: frontend
          files: frontend/coverage/cobertura-coverage.xml
